# Generated by Django 4.0.2 on 2022-02-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palettemodel',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
