# Generated by Django 4.0.2 on 2022-02-19 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colorApp', '0002_palettemodel_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='palettemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='palette_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
